sonar.projectKey=denivladislav_go-project-244
sonar.organization=denivladislav

sonar.sources=.
sonar.tests=.

sonar.test.inclusions=**/*_test.go
sonar.exclusions=**/*_test.go,**/.scannerwork/**,**/.github/**

sonar.go.coverage.reportPaths=coverage.out
